
version: 2

sources:
  - name: RAW
    database: DBT_DB
    schema: DBT_HUB
    tables:
      - name: RAW_CUSTOMERS
        description: "Table containing raw customer data."
        columns:
          - name: customer_id
            description: "Unique identifier for each customer."
          - name: customer_name
            description: "Name of the customer."
          - name: customer_email
            description: "Email address of the customer."
          - name: customer_phone
            description: "Phone number of the customer."   
      
  - name: RAW
    database: DBT_DB
    schema: DBT_HUB
    tables:
      - name: RAW_ORDERS 
        description: "Table containing raw order data."
        columns:
          - name: order_id
            description: "Unique identifier for each order."
          - name: customer_id
            description: "Identifier linking the order to a customer."
          - name: order_date
            description: "Date when the order was placed."
          - name: order_amount
            description: "Total amount of the order."

     
